### ISSUE TITLE
It shouldn't be possible to select a range with disabled dates inside

### ISSUE THREAD

**Issue by OzoTek** [werein/react-native-dates#11]
Hello,

I just noticed a bug where we can select a date range between 2 available dates, even if there are some disabled inside.

Showcase :

With available/disabled dates like this :

![screenshot_20170313-144536_01](https://cloud.githubusercontent.com/assets/6436053/23859646/3953133c-07fc-11e7-9477-748210290b78.png)

I am able to do this :

![screenshot_20170313-144544_01](https://cloud.githubusercontent.com/assets/6436053/23859665/4d5f4684-07fc-11e7-8005-4dd949a25054.png)

Otherwise, the lib is awesome ;)

Thanks.

**Comment by jirikolarik** [comment]
Hi,

this handling is not included in a lib, try to use something like this:

```javascript
const onDatesChange = ({ startDate, endDate, focusedInput }) => {
  moment.range(startDate, endDate).by('days', (day) => {
    if (isDateBlocked(day)) {
      return console.log(day, 'is blocked');
    }
  });

  this.setState({ ...this.state, focus: focusedInput }, () =>
    this.setState({ ...this.state, startDate, endDate })
  );
}
```

this code shouldn't update state with `startDate` and `endDate` in your state but print into console information that you cannot select this time range. There could be some nice popup message or any other information, but implementation is up to you :)

**Comment by OzoTek** [comment]
Thanks for the answer, it causes my app to freeze though...

**Comment by jirikolarik** [comment]
My bad, I'll try to reproduce it locally and then let you know

**Comment by OzoTek** [comment]
I've done a Pull Request for this issue, let me know :)

**Comment by GrishmaM** [comment]
@OzoTek  is this working for you ?
 i'm getting **Unhandled JS Exception: _moment2.default.range is not a function**
do you have any solution for this ?

**Comment by OzoTek** [comment]
I'm using `"moment-range": "^2.2.0"` as a dependency in my project, it works well. I think there have been some breaking changes with the v3 that are not supported by the lib.

**Comment by GrishmaM** [comment]
thanx it worked for me

**Comment by jirikolarik** [comment]
You fixed it with https://github.com/werein/react-native-dates/pull/13 right @OzoTek ?

**Comment by OzoTek** [comment]
Yes, I'm closing.
