### ISSUE TITLE
Date not focused if the hour changes

### ISSUE THREAD

**Issue by OzoTek** [werein/react-native-dates#12]
Hello,

I noticed another bug :

If we change the hour of a selected date, it unfocuses it, in a scenario of selecting a date and then its time it feels weird to have the period or date removed, even though the variables are properly set.

From what I saw, the date is selected only if the time is 00:00.

If you need any help fixing one of the issues I opened let me know, maybe I can open a PR, I need this to work quite fast so it's better if I can help making it faster :).

Thanks.

**Comment by jirikolarik** [comment]
Hi, if you can then it's great!:)

**Comment by DaneW** [comment]
This issue can be closed now as the #21 PR has been merged to fix this issue.
