### ISSUE TITLE
Excuse me, can't set up the Chinese?

### ISSUE THREAD

**Issue by pheromone** [werein/react-native-dates#15]
<img width="383" alt="5c6231fa-f013-4e43-8e79-30a04e1186e9" src="https://cloud.githubusercontent.com/assets/14305431/26089076/89d749dc-3a2d-11e7-84ed-0035a4f2ef73.png">

**Comment by jirikolarik** [comment]
I'm sorry, but I didn't count with chinese :( i'll gladly except pr with more localisations
