### ISSUE TITLE
Changing the selected date color

### ISSUE THREAD

**Issue by happy2share** [werein/react-native-dates#16]
First of all this is not an issue, needs some direction.
I am trying to change the selected date colour. I tried with Styles available in module index.js. But no use.
Can anyone please help me out to change the background colour of the date selected from default blue

**Comment by jirikolarik** [comment]
This branch should have custom styles enabled - https://github.com/werein/react-native-dates/pull/17
It is not tested yet

**Comment by a-tokyo** [comment]
Shouldn't we close this?

**Comment by jirikolarik** [comment]
yop
