### ISSUE TITLE
Undefined moment2.default.range(currentDate.clone().startOf(iosweek))

### ISSUE THREAD

**Issue by xuananpham93** [werein/react-native-dates#23]
@jirikolarik 
Hi bro. I have problem when use library. How can I fix it?

![screenshot-2017-12-25_10 56 28 436](https://user-images.githubusercontent.com/16789892/34332425-e6baa27c-e962-11e7-89f6-17a76b818385.png)

**Comment by pohsiu** [comment]
u should install module moment-range
