### ISSUE TITLE
Only future dates can be selected

### ISSUE THREAD

**Issue by jdcc2** [werein/react-native-dates#5]
I cannot find a way to select past dates. I looked at the source, and isFutureDate seems to be hardcoded as a requirement for a date to be selectable. Can this changed into an option?

**Comment by jirikolarik** [comment]
You're absolutely right, my use case didn't allowed past dates, but this should be optional. I'll do that later on.

**Comment by brendanscarano** [comment]
hey @jirikolarik I would love to use this calendar however I will be primarily using it for past dates - any update when this feature may be available?

**Comment by jdcc2** [comment]
I created a pull request that adds a history option and allows selecting past dates.

**Comment by jirikolarik** [comment]
I've removed code which blocks previous dates in https://github.com/werein/react-native-dates/tree/feature/previous-dates user still can achieve this functionality by passing method provided in readme.

@jdcc2 thanks for this PR, I've been thinking about doing the same, but in this case you cannot modify if you also want to block current date, if we keep only `isDateBlocked` function without any other component modifications, you can simply use `isBefore`, `isBeforeOrAfter` methods of the date (`moment`)

What do you think guys? @jdcc2 @brendanscarano

**Comment by jdcc2** [comment]
@jirikolarik I think your solution is more flexible. Did you also look at the small changes I made when comparing if two days are the same in Week? Because isSameOrAfter() needs the 'day' argument when checking for equality on the day level. (I don't remember the case in which not doing this resulted in strange behavior)

**Comment by brendanscarano** [comment]
@jirikolarik this was the functionality I was looking for - thanks!

I went to run the project myself and was met with some Unmet Peer Dependency warnings...
Also what is the command for running the project? I didn't see a .xcodeproj anywhere, or any npm scripts to run... I'm still pretty new to React Native development so I apologize if I'm missing something obvious.
Thanks!

![screen shot 2017-01-25 at 6 20 49 am](https://cloud.githubusercontent.com/assets/6002060/22288785/73702cfe-e2c6-11e6-8f5d-2000a0b3a07c.png)

**Comment by jirikolarik** [comment]
Cool. Use it as any other package in your react-native project.. Add it to your current `packages.json` and `import Dates from 'react-native-calendar'` then you should be good to go.

**Comment by jirikolarik** [comment]
This project doesn't contain runnable application, I'll prepare and example over this weekend

**Comment by brendanscarano** [comment]
thanks @jirikolarik - I got it to run in my project. Any plans to accept the PR into master this weekend to allow dates in the past to be selected?

**Comment by jirikolarik** [comment]
Cool. Sure, just have to fix failing build.

**Comment by brendanscarano** [comment]
hey @jirikolarik - any update on the failing build? I would love to continue using this library in my app and be able to select dates in the past - thanks!!

**Comment by jirikolarik** [comment]
Try it now :)

**Comment by brendanscarano** [comment]
hey @jirikolarik - I'm still having trouble trying to select dates in the past. I anticipated the code below would let me select any date in 2017 however any date before today is not clickable.

In my code I have:
`<Dates
    onDatesChange={onDatesChange}
    isDateBlocked={(date) => date.isBefore(moment(), 'year')}
    startDate={this.state.startDate}
    endDate={this.state.endDate}
    focusedInput={this.state.focus}
/>`

<img width="374" alt="screen shot 2017-02-12 at 8 52 15 pm" src="https://cloud.githubusercontent.com/assets/6002060/22868542/2f2c71f8-f165-11e6-81e4-bb634a89df9d.png">

Also, is `isDateBlocked` a required prop? If I want to let my users select any date, in the past or future, what prop can I pass to `<Dates />` to allow this to happen?

Thanks for the help!

**Comment by jirikolarik** [comment]
Right now it is required property, but you can say, that all days are allowed like this:

```javascript
<Dates
    onDatesChange={onDatesChange}
    isDateBlocked={(date) => false}
    startDate={this.state.startDate}
    endDate={this.state.endDate}
    focusedInput={this.state.focus}
    range
/>
```

I'll publish latest release to npm, right now it's still only here on github

**Comment by brendanscarano** [comment]
I have the same function for my isDateBlocked and I'm still only able to select dates from today and later. I am however running the project from npm in my own project. Will I only see this change to select later dates once the latest release is published to npm?

**Comment by brendanscarano** [comment]
Hi @jirikolarik - any update on this? Once this update is published to npm, will I be able to select dates in the past?

**Comment by brendanscarano** [comment]
Hi @jirikolarik - I have the code you included above 
`<Dates
    onDatesChange={onDatesChange}
    isDateBlocked={(date) => false}
    startDate={this.state.startDate}
    endDate={this.state.endDate}
    focusedInput={this.state.focus}
    range
/>`

however I still cannot select dates in the past... do you have a timeline for when this latest release with this fix will be published to npm?

**Comment by jirikolarik** [comment]
Now it's available on npm, if you have `isDateBlocked={(date) => false}` then all of the dates will be available, what you can do is: `isDateBlocked={(date) => date.isBefore(moment(), 'day')}` in this case all dates before today (previous dates) are considered as blocked

**Comment by brendanscarano** [comment]
Thank you @jirikolarik

**Comment by jirikolarik** [comment]
Does it work now?:) Can we close this?

**Comment by brendanscarano** [comment]
It works great now, it can be closed.
Thanks again for the help!
