### ISSUE TITLE
_moment2.default.range is not a function

### ISSUE THREAD

**Issue by obukhow** [werein/react-native-dates#8]
I have such problem in my app
![2017-02-17 12 42 19](https://cloud.githubusercontent.com/assets/621014/23060386/f1828bfc-f516-11e6-93a5-1a0d3a3e01a5.png)

**Comment by HamiltonWang** [comment]
me too

**Comment by jirikolarik** [comment]
This is resolved by now. It was caused due to mismatched versions of `moment-range`

**Comment by OzoTek** [comment]
Hi, just downloaded the lib, and I have the same issue, have you pushed the fix yet or will it come soon?
